id: 360049860611
url: >-
  https://circleci.zendesk.com/api/v2/help_center/en-us/articles/360049860611.json
html_url: >-
  https://support.circleci.com/hc/en-us/articles/360049860611-I-have-an-error-We-encountered-a-problem-adding-your-identity-to-CircleCI-when-I-m-trying-re-connect-another-Github-account-to-my-project
author_id: 400228627014
comments_disabled: true
draft: false
promoted: false
position: 0
vote_sum: -2
vote_count: 2
section_id: 115003332287
created_at: '2020-09-17T19:44:38Z'
updated_at: '2021-01-12T01:40:56Z'
name: >-
  I have an error "We encountered a problem adding your identity to
  CircleCI...", when I'm trying re-connect another Github account to my project
title: >-
  I have an error "We encountered a problem adding your identity to
  CircleCI...", when I'm trying re-connect another Github account to my project
source_locale: en-us
locale: en-us
outdated: false
outdated_locales: []
edited_at: '2020-10-22T06:56:22Z'
user_segment_id: null
permission_group_id: 237867
label_names:
  - github
  - permissions
body: >-
  <p><img
  src="https://support.circleci.com/hc/article_attachments/360069200652/mceclip0.png"
  alt="mceclip0.png"></p>

  <p>If you encounter this error when authorizing another GitHub or BitBucket
  account to your CircleCI account, this means that the account has already been
  authorized with CircleCI. This can be solved by revoking CircleCI's OAuth
  token within your VCS account, and attempting to authorize again.</p>

  <p>If you still are unable to connect your VCS account, please <a
  href="https://support.circleci.com/hc/en-us/requests/new"
  target="_self">submit a new request</a> and we will manually disconnect your
  VCS account for you.</p>
